apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: smtp4dev-data
  name: smtp4dev-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
